#!/bin/bash

_utility_completions()
{
	COMPREPLY=()
	cur=${COMP_WORDS[COMP_CWORD]}
	prev=${COMP_WORDS[COMP_CWORD-1]}
	if [ $COMP_CWORD -eq 1 ]; then
		COMPREPLY=( $(compgen -W "cleanfan get set" -- $cur) )
	elif [ $COMP_CWORD -eq 2 ]; then
		COMPREPLY=( $(compgen -W "battery performance" -- $cur) )
	elif [ $COMP_CWORD -eq 3 ]; then
		case $prev in
			"battery")
				COMPREPLY=( $(compgen -W "conservation normal rapidcharge" -- $cur) )
				;;
			"performance")
				COMPREPLY=( $(compgen -W "balance conservation extreme" -- $cur) )
				;;
			*)
				;;
		esac
	fi

	return 0
}

complete -F _utility_completions utility
